# Generated by Django 6.0 on 2025-12-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('arranger', models.CharField(default='Aaron Teng', max_length=50)),
                ('vrsn', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
