# Generated by Django 6.0 on 2025-12-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='synopsis',
            field=models.TextField(default=None, null=True),
        ),
    ]
