# Generated by Django 6.0 on 2025-12-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0002_db_seed'),
        ('sheetmusic', '0003_addSynopsis'),
    ]

    operations = [
    ]
