# Generated by Django 6.0 on 2025-12-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    def seed(apps, schema_editor):
        Sheet = apps.get_model('sheetmusic', 'Sheet')
        Sheet.objects.create(
            title = "2002",
            artist = "Anne-Marie",
            vrsn="11-17"
        )
        Sheet.objects.create(
            title="Shelter",
            artist="Tori Kelly",
            vrsn="12-4"
        )
        Sheet.objects.create(
            title="Bending My Rules",
            artist="FLO",
            vrsn="12-31"
        )

    dependencies = [
        ('sheetmusic', '0004_merge_0002_db_seed_0003_addSynopsis'),
    ]

    operations = [
        migrations.RunPython(seed)
    ]
