# Generated by Django 6.0 on 2026-01-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0005_db_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='instr',
            field=models.CharField(default='SMATBaB Choir', max_length=50),
            preserve_default=False,
        ),
    ]
