# Generated by Django 6.0 on 2026-01-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0006_addinstrfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
