# Generated by Django 6.0 on 2026-01-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0007_addPriceToSheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=512)),
                ('customer_id', models.CharField(max_length=512)),
                ('customer_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('fulfilled', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheetmusic.sheet')),
            ],
        ),
    ]
