# Generated by Django 6.0 on 2026-01-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
