# Generated by Django 6.0 on 2026-01-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0009_removeCustomerIDFromOrder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=60)),
                ('responded', models.BooleanField(default=False)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=60)),
                ('responded', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('use_context', models.TextField()),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
