# Generated by Django 6.0 on 2026-01-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0010_feedback_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='info',
            new_name='additional_info',
        ),
        migrations.RemoveField(
            model_name='request',
            name='subject',
        ),
    ]
