# Generated by Django 6.0 on 2026-01-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0011_rename_info_request_additional_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='title',
            new_name='arr_name',
        ),
    ]
