# Generated by Django 6.0 on 2026-01-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0013_feedback_created_at_request_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='arr_name',
            new_name='arrangement_name',
        ),
        migrations.AddField(
            model_name='request',
            name='original_artist',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
