# Generated by Django 6.0 on 2026-01-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0014_rename_arr_name_request_arrangement_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='body',
            new_name='context',
        ),
    ]
