# Generated by Django 6.0 on 2026-01-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0015_rename_body_feedback_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='request',
            name='original_artist',
            field=models.CharField(default='', max_length=50),
        ),
    ]
