# Generated by Django 6.0 on 2026-01-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0016_alter_feedback_subject_alter_request_original_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='product_id',
            field=models.CharField(default='asdf', max_length=30),
            preserve_default=False,
        ),
    ]
