# Generated by Django 6.0 on 2026-01-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0018_remove_sheet_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='product_id',
            field=models.CharField(default='Asdf', max_length=30),
            preserve_default=False,
        ),
    ]
