# Generated by Django 6.0 on 2026-01-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetmusic', '0019_sheet_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='product_id',
        ),
    ]
